version: '3.8'

services:
  nest-api:
    networks:
      - my-network
    container_name: nest-music-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    networks:
      - my-network
    container_name: db-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

networks:
  my-network:
    name: music_api_network
    driver: bridge
volumes:
  postgres-db-volume:
    name: postgres-db-volume